---
# yamllint disable rule:line-length
name: Deploy and Bump
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  CLOUDFLARE_EMAIL=${{ secrets.CLOUDFLARE_EMAIL}}
  CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2.0.3
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: main
          token: ${{ github.token }}
          fetch-depth: '0'
      - name: Config Terraform plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache
      - name: Cache Terraform
        uses: actions/cache@v3.2.4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - name: Terraform Init
        id: init
        run: terraform init example/examplea
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve example/examplea
  version:
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DEFAULT_BUMP: patch
          WITH_V: true
    needs: [terraform]
